prefix dbo: <http://dbpedia.org/ontology/> 
prefix owl: <http://www.w3.org/2002/07/owl#> 
prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#> 
prefix schema: <https://schema.org/> 
prefix xsd: <http://www.w3.org/2001/XMLSchema#> 
prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> 
prefix dbr: <http://dbpedia.org/resource/> 

SELECT ?recipe (COUNT(DISTINCT ?c) AS ?num_Calories)
WHERE {
  ?recipe a schema:Recipe .
  ?recipe schema:nutrition ?n .
  ?n schema:calories ?c .
}
GROUP BY ?recipe 
HAVING (COUNT(DISTINCT ?c) > 1)


